name: pull

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:
  schedule:
    - cron: 29 8 * * *  # about 1:29am PDT

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: t
jobs:
  - id: files
    uses: jitterbit/get-changed-files@v1
  - run: |
      echo ${{ steps.files.outputs.all }}
      for changed_file in ${{ steps.files.outputs.all }}; do
        echo "Do something with this ${changed_file}."
      done