name: BC Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
    branches-ignore:
      - nightly
  workflow_dispatch:

jobs:
  create-alerts:
    runs-on: ubuntu-20.04
    outputs:
      alerts: ${{ steps.alert_creation_step.outputs.script-output }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Python Packages
        run: |
          pip3 install rockset==1.0.3
          pip3 install boto3==1.19.12

      - name: Create alerts
        run: |
          output=$(python "tools/alerts/create_alerts.py")
          echo "uploading following alerts"
          echo "$output"
          echo "script-output=$output" >> "$GITHUB_OUTPUT"
        id: alert_creation_step

  upload-alerts:
    needs: create-alerts
    uses: pytorch/test-infra/.github/actions/upload-alerts@f763034f4fa84008c1eebe4aeadf4931b98b5b53
    with:
      alerts: '${{ needs.create-alerts.outputs.alerts }}'
      organization: "pytorch"
      repo: "pytorch"
    secrets: inherit
  bc_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Run BC Lint Action
        uses: pytorch/test-infra/.github/actions/bc-lint@main
        with:
          repo: ${{ github.event.pull_request.head.repo.full_name }}
          base_sha: ${{ github.event.pull_request.base.sha }}
          head_sha: ${{ github.event.pull_request.head.sha }}
          suppression: ${{ contains(github.event.pull_request.labels.*.name, 'suppress-api-compatibility-check') || contains(github.event.pull_request.labels.*.name, 'suppress-bc-linter') }}
          docs_link: 'https://github.com/pytorch/test-infra/wiki/BC-Linter'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
