# upload alerts every 10 minutes

name: Upload Alerts to AWS/Rockset

on:
  pull_request:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  upload-alerts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Python Packages
        run: |
          pip3 install rockset==1.0.3
          pip3 install boto3==1.19.12

      - name: Create alerts
        run: |
          output=$(python "tools/alerts/create_alerts.py")
          echo "uploading following alerts"
          echo "$output"
          echo "script-output=$output" >> "$GITHUB_OUTPUT"
        id: alert_creation_step
      - name: Upload alerts
        uses: pytorch/test-infra/.github/actions/upload-alerts@74bede79c34990cd3efd714408c5dd2fc25a658a
        with:
          alerts: '${{ steps.alert_creation_step.outputs.script-output }}'
          organization: "pytorch"
          repo: "pytorch"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true